from __future__ import annotations

import json
from typing import Any

from .credibility import SOURCE_TYPES, TIER_DEFINITIONS
from .schema import (
    COORDINATES_ONLY_ISO3,
    COORDINATE_ATTRIBUTES,
    DEFINITION_VALUES,
    GCCS_ATTRIBUTES,
    normalize_scalar,
    parse_tristate_bool,
    GAP_FILL_ATTRIBUTES,
    IDENTITY_ATTRIBUTES,
    is_blank,
)


# Only these units are ever requested, so the agent is never asked to invent one.
ATTRIBUTE_UNITS = {
    "annual_incoming_waste_metric_tonnes": "metric tonnes/year",
    "waste_in_place_metric_tonnes": "metric tonnes",
    "found_latitude": "decimal degrees",
    "found_longitude": "decimal degrees",
    "opening_year": "year",
    "closing_year": "year",
    "waste_depth": "meters",
    "area_square_meters": "square meters",
    "gccs_ch4_flared_metric_tonnes": "metric tonnes CH4",
    "gccs_ch4_generated_metric_tonnes": "metric tonnes CH4",
    "gccs_ch4_collected_metric_tonnes": "metric tonnes CH4",
    "gccs_ch4_flow_to_project_metric_tonnes": "metric tonnes CH4",
    "gccs_collection_efficiency": "fraction between 0 and 1",
}

ATTRIBUTE_GUIDANCE = {
    "facility_status": "Allowed values only: Active, Inactive. A closed or former site is Inactive.",
    "facility_type": "Allowed values only: Sanitary Landfill, Controlled Dumpsite, Dumpsite, Incineration Facility.",
    "cover_types": "Array. Allowed members only: clay cover, organic cover, sand cover, other soil mixture.",
    "has_landfill_gas_collection": "Yes, No, or Unknown.",
    "opening_year": "Four-digit year the facility opened.",
    "closing_year": (
        "Four-digit year the facility closed or is expected to close. REQUIRED whenever the "
        "facility is closed or inactive - a closure date almost always exists in news coverage, "
        "a council resolution, or a closure order. Search for it specifically."
    ),
    "annual_incoming_waste_metric_tonnes": (
        "Waste accepted per year. Report the source's original unit; the pipeline converts. "
        "Distinguish metric tonnes from US short tons. If the source just says 'tons', keep the "
        "number in value and set unit to 'ambiguous tons'. Never put words in value."
    ),
    "waste_in_place_metric_tonnes": (
        "Total waste mass in place (a stock, not a rate). Report the source's original unit."
    ),
    "area_square_meters": (
        "Surface area of the landfill footprint containing waste. Report the source's original "
        "unit - hectares, acres, square feet, square kilometres or square metres - and the "
        "pipeline converts. This is the waste footprint, not the whole property or parcel."
    ),
    "waste_depth": (
        "Average depth of waste. Report the NUMBER and the source's original unit (feet or "
        "meters) - the pipeline converts to metres and bins the result into a depth category. "
        "Do not return a category yourself, and never put words or a band in value. Must be "
        "greater than zero: a reported zero is not a measurement."
    ),
    "has_cover": "Whether any cover material is present. Yes, No, or Unknown.",
    "has_biocover": (
        "Whether the facility has a biocover - an engineered organic or biologically active "
        "cover intended to oxidise methane. Yes, No, or Unknown. A plain soil, clay or sand "
        "cover is NOT a biocover; answer No for those. Do not infer one from the mere presence "
        "of cover material."
    ),
    "gccs_ch4_flared_metric_tonnes": (
        "Methane sent to flares. Report the source's original unit. If the source gives a gas "
        "VOLUME, say whether it is methane or raw landfill gas - raw landfill gas cannot be "
        "converted without a methane fraction, so give that fraction if the source states it."
    ),
    "gccs_ch4_generated_metric_tonnes": "Methane generated by the landfill. Same unit rules as flared.",
    "gccs_ch4_collected_metric_tonnes": "Methane captured by the collection system. Same unit rules as flared.",
    "gccs_ch4_flow_to_project_metric_tonnes": (
        "Methane routed to an energy recovery project. Same unit rules as flared."
    ),
    "gccs_energy_project_type": (
        "Array. Allowed members only: Electricity Generation, Direct Use, Renewable Natural Gas, "
        "Other. Flaring alone is NOT an energy project - leave empty if gas is only flared. "
        "(This 'Other' is a database enum value for project type, unrelated to source_type.)"
    ),
    "gccs_current_project_status": (
        "Array. Allowed members only: Operational, Under Construction, Planned, Closed."
    ),
    "gccs_collection_efficiency": (
        "Fraction of generated landfill gas that is collected, as a value between 0 and 1. "
        "If the source gives a percentage, report the number and set unit to '%'."
    ),
    "found_site_name": "The source's exact official or canonical name for this facility.",
    "found_latitude": "Source-reported latitude only. Never infer from an address or nearby place.",
    "found_longitude": "Source-reported longitude only. Never infer from an address or nearby place.",
}


# Name fragments that signal a closed site, so the prompt can push on closing_year up front.
CLOSURE_NAME_HINTS = ("closed", "close)", "former", "abandoned", "decommission", "shut")


def looks_inactive(site: dict[str, Any]) -> bool:
    """Whether we already have reason to believe this facility is closed."""
    if normalize_scalar(site.get("facility_status")).lower() == "inactive":
        return True
    name = normalize_scalar(site.get("site_name")).lower()
    return any(hint in name for hint in CLOSURE_NAME_HINTS)


def has_gas_collection(site: dict[str, Any]) -> bool:
    """Whether the baseline states this facility has a gas collection system.

    GCCS attributes are requested only when this is true. Unknown counts as not-yet-known rather
    than absent, and is picked up on a later pass: `has_landfill_gas_collection` is itself
    gap-filled, so once a pass establishes it, `refresh-seed` promotes it into the baseline and
    the next search requests that facility's GCCS attributes. Nothing is lost, only deferred.
    """
    return parse_tristate_bool(site.get("has_landfill_gas_collection"))[0] is True


def coordinates_only(site: dict[str, Any]) -> bool:
    """Whether this facility's country is scoped to coordinates alone."""
    return normalize_scalar(site.get("country_iso3")).upper() in COORDINATES_ONLY_ISO3


def location_is_inexact(site: dict[str, Any]) -> bool:
    """Whether the recorded location is positively flagged as not exact.

    Unknown is not inexact: only an explicit FALSE asks for a coordinate search.
    """
    return parse_tristate_bool(site.get("is_location_exact"))[0] is False


def requested_attributes(site: dict[str, Any]) -> list[str]:
    """Identity always; metadata only where the facility's baseline is empty (gap-fill, Q29).

    GCCS attributes are requested only for facilities known to have a gas collection system.
    Some countries are scoped to coordinates alone (COORDINATES_ONLY_ISO3).
    """
    if coordinates_only(site):
        # Coordinates are worth confirming only where the recorded location is flagged inexact;
        # everything else for these facilities is government-sourced and left alone.
        return list(COORDINATE_ATTRIBUTES) if location_is_inexact(site) else []

    requested = list(IDENTITY_ATTRIBUTES)
    gas_present = has_gas_collection(site)
    for field in GAP_FILL_ATTRIBUTES:
        if not is_blank(site.get(field)):
            continue
        if field in GCCS_ATTRIBUTES and not gas_present:
            continue
        requested.append(field)
    return requested


def build_site_prompt(site: dict[str, Any], attributes: list[str] | None = None) -> str:
    attributes = attributes if attributes is not None else requested_attributes(site)

    site_context = {
        key: site.get(key)
        for key in (
            "site_id",
            "site_name",
            "original_site_name",
            "source_language",
            "country_iso3",
            "latitude",
            "longitude",
            "input_area_square_meters",
            "municipality",
            "admin1",
            "admin2",
            "formatted_address",
        )
        if site.get(key)
    }

    targets = [
        {
            "attribute_name": name,
            "unit": ATTRIBUTE_UNITS.get(name, ""),
            "guidance": ATTRIBUTE_GUIDANCE.get(name, ""),
        }
        for name in attributes
    ]

    closure_focus = ""
    if "closing_year" in attributes and looks_inactive(site):
        closure_focus = (
            "\nThis facility appears to be closed or inactive already, so a closure date should\n"
            "exist. Search specifically for it - closure orders, council resolutions, news\n"
            "coverage of the shutdown - and return closing_year. Say in search_notes what you\n"
            "tried if you genuinely cannot find one.\n"
        )

    output_contract = {
        "site_id": site.get("site_id"),
        "attributes": [
            {
                "attribute_name": "One attribute_name from the Target attributes list",
                "value": "Candidate value",
                "unit": "Source's original unit, or blank",
                "value_basis": "Direct / Inferred / Conflicting / Not found",
                "confidence_score": "High / Medium / Low / Excluded candidate",
                "value_date": "YYYY-MM-DD, YYYY-MM, or YYYY",
                "evidence_summary": "Short source-backed explanation",
                "search_terms_used": "Search terms and languages used",
                "sources": [
                    {
                        "source_title": "Title",
                        "publisher": "Publisher, operator, or regulator",
                        "source_type": "One value from Definitions.source_type",
                        "publication_date": "YYYY-MM-DD or blank",
                        "url": "https://...",
                        "language": "English / local language",
                        "paywall_flag": False,
                        "quoted_evidence_short": "Short quote from the source",
                    }
                ],
            }
        ],
        "unverified_leads": [],
        "search_notes": "Languages, search terms, and gaps.",
    }

    definitions = {
        "attribute_name": attributes,
        "source_type": SOURCE_TYPES,
        "source_tier_rubric": TIER_DEFINITIONS,
        "facility_status": DEFINITION_VALUES["facility_status"],
        "facility_type": DEFINITION_VALUES["facility_type"],
        "cover_type": DEFINITION_VALUES["cover_type"],
        "gccs_energy_project_type": DEFINITION_VALUES["gccs_energy_project_type"],
        "gccs_current_project_status": DEFINITION_VALUES["gccs_current_project_status"],
        "boolean_unknown": DEFINITION_VALUES["boolean_unknown"],
        "value_basis": DEFINITION_VALUES["value_basis"],
        "confidence_score": DEFINITION_VALUES["confidence_score"],
    }

    return f"""You are a waste-sector data discovery agent for WasteMAP.

Task:
Find source-backed data for this waste disposal site. Search in English and in the
local language, using the site name, coordinates, municipality, and admin names.

Names:
- site_name has been machine-translated into English. It is often NOT what local
  sources call this facility, and searching it alone is the most common reason a
  real site looks like it has no coverage.
- original_site_name, when present, is the name the source dataset actually
  recorded, in source_language. Search THIS name in the local language first -
  permits, municipal records and local news will use it, not the translation.
- Search both. Treat them as one facility with two names, never as two
  candidates: agreeing on the translated name alone is not identity confirmation.
- Return found_site_name exactly as your source spells it, in whatever script or
  language that source uses. Do not translate it back.

Only the attributes listed below are wanted. Everything else about this facility is
already known and must not be researched or returned.

Target attributes:
{json.dumps(targets, indent=2, ensure_ascii=False)}

Site context:
{json.dumps(site_context, indent=2, ensure_ascii=False)}

Definitions:
{json.dumps(definitions, indent=2, ensure_ascii=False)}

{closure_focus}
Status and closure:
- If your sources show the facility is closed, inactive, or no longer accepting waste, return
  facility_status = Inactive AND search for closing_year in the same pass. A closed site
  without a closure year is an incomplete answer.

Identity first:
- found_site_name, found_latitude and found_longitude establish that you found the
  RIGHT facility. Always return them when a source supports them.
- If you cannot confirm you found this specific facility, return an empty attributes
  list and explain why in search_notes. Do not return data for a different site.

Source requirements:
- Every returned attribute needs at least one clickable source URL.
- Classify each source with source_type from Definitions.source_type. Do not invent
  new source types and do not combine two with a slash. There is no catch-all: if no
  listed type genuinely fits the source, put the finding in unverified_leads rather
  than guessing a type.
- Always give publication_date when the source shows one. An undated source is
  treated as less credible, so a date materially changes how the value is used.
- Do not assign a source tier. The pipeline assigns credibility from source_type
  and publisher.
- Attach every supporting source to the attribute. Agreement between independent
  sources is recorded, so list them all rather than only the best one.

Value requirements:
- Use only the allowed categorical values in Definitions. If the true value is not
  among them, put it in unverified_leads instead of forcing a wrong category.
- Report the source's original unit in the unit field. The pipeline converts.
- value must hold only the value itself. For numeric attributes that means digits, never
  words, ranges in prose, or unit text.
- Gas capture attributes only apply if the facility actually has a gas collection system. If it
  does not, omit them rather than returning zeros.
- Label anything not directly stated by the source as value_basis = Inferred.
- Put uncertain or unsourced findings in unverified_leads, not attributes.
- If nothing is found, return an empty attributes list and explain in search_notes.

Output requirements:
- Return strict JSON only. No markdown, no prose outside JSON.

JSON output contract:
{json.dumps(output_contract, indent=2, ensure_ascii=False)}
"""
